export type PuzzleOpeningTagCount = { tag: string; puzzleCount: number }

// Source: user-provided SQL export (count > 300) from puzzles_v2 OpeningTags.
export const PUZZLE_OPENING_TAG_COUNTS_GT300: PuzzleOpeningTagCount[] = [
  { tag: 'Sicilian_Defense', puzzleCount: 17678 },
  { tag: 'French_Defense', puzzleCount: 7410 },
  { tag: 'Queens_Pawn_Game', puzzleCount: 6782 },
  { tag: 'Italian_Game', puzzleCount: 6426 },
  { tag: 'Caro-Kann_Defense', puzzleCount: 6412 },
  { tag: 'Scandinavian_Defense', puzzleCount: 4893 },
  { tag: 'Queens_Gambit_Declined', puzzleCount: 4268 },
  { tag: 'English_Opening', puzzleCount: 3632 },
  { tag: 'Ruy_Lopez', puzzleCount: 3394 },
  { tag: 'Indian_Defense', puzzleCount: 3209 },
  { tag: 'Scotch_Game', puzzleCount: 3131 },
  { tag: 'Philidor_Defense', puzzleCount: 2150 },
  { tag: 'Russian_Game', puzzleCount: 1777 },
  { tag: 'Kings_Gambit_Accepted', puzzleCount: 1776 },
  { tag: 'Zukertort_Opening', puzzleCount: 1722 },
  { tag: 'Four_Knights_Game', puzzleCount: 1672 },
  { tag: 'Indian_Defense_Other_variations', puzzleCount: 1656 },
  { tag: 'Vienna_Game', puzzleCount: 1650 },
  { tag: 'Modern_Defense', puzzleCount: 1635 },
  { tag: 'Caro-Kann_Defense_Other_variations', puzzleCount: 1634 },
  { tag: 'Italian_Game_Two_Knights_Defense', puzzleCount: 1623 },
  { tag: 'Pirc_Defense', puzzleCount: 1603 },
  { tag: 'Bishops_Opening', puzzleCount: 1555 },
  { tag: 'Queens_Pawn_Game_Accelerated_London_System', puzzleCount: 1521 },
  { tag: 'Kings_Pawn_Game', puzzleCount: 1502 },
  { tag: 'Slav_Defense', puzzleCount: 1493 },
  { tag: 'French_Defense_Advance_Variation', puzzleCount: 1331 },
  { tag: 'English_Opening_Kings_English_Variation', puzzleCount: 1297 },
  { tag: 'Philidor_Defense_Other_variations', puzzleCount: 1295 },
  { tag: 'Queens_Pawn_Game_Other_variations', puzzleCount: 1285 },
  { tag: 'Sicilian_Defense_Closed', puzzleCount: 1258 },
  { tag: 'Caro-Kann_Defense_Advance_Variation', puzzleCount: 1212 },
  { tag: 'Sicilian_Defense_Old_Sicilian', puzzleCount: 1209 },
  { tag: 'French_Defense_Exchange_Variation', puzzleCount: 1167 },
  { tag: 'Sicilian_Defense_Alapin_Variation', puzzleCount: 1153 },
  { tag: 'Queens_Gambit_Accepted', puzzleCount: 1128 },
  { tag: 'Benoni_Defense', puzzleCount: 1125 },
  { tag: 'Modern_Defense_Other_variations', puzzleCount: 1113 },
  { tag: 'Sicilian_Defense_Bowdler_Attack', puzzleCount: 1096 },
  { tag: 'Nimzo-Larsen_Attack', puzzleCount: 1078 },
  { tag: 'Nimzowitsch_Defense', puzzleCount: 1071 },
  { tag: 'Italian_Game_Classical_Variation', puzzleCount: 1070 },
  { tag: 'Alekhine_Defense', puzzleCount: 1068 },
  { tag: 'Kings_Indian_Defense', puzzleCount: 1039 },
  { tag: 'Scandinavian_Defense_Mieses-Kotroc_Variation', puzzleCount: 1021 },
  { tag: 'Scandinavian_Defense_Modern_Variation', puzzleCount: 1010 },
  { tag: 'Pirc_Defense_Other_variations', puzzleCount: 982 },
  { tag: 'Sicilian_Defense_Najdorf_Variation', puzzleCount: 973 },
  { tag: 'French_Defense_Knight_Variation', puzzleCount: 970 },
  { tag: 'Horwitz_Defense', puzzleCount: 958 },
  { tag: 'Horwitz_Defense_Other_variations', puzzleCount: 958 },
  { tag: 'Sicilian_Defense_Modern_Variations', puzzleCount: 942 },
  { tag: 'Scotch_Game_Other_variations', puzzleCount: 938 },
  { tag: 'Scandinavian_Defense_Main_Line', puzzleCount: 874 },
  { tag: 'Bird_Opening', puzzleCount: 873 },
  { tag: 'Owen_Defense', puzzleCount: 872 },
  { tag: 'Englund_Gambit', puzzleCount: 865 },
  { tag: 'Kings_Gambit_Declined', puzzleCount: 844 },
  { tag: 'Owen_Defense_Other_variations', puzzleCount: 839 },
  { tag: 'Italian_Game_Giuoco_Pianissimo', puzzleCount: 828 },
  { tag: 'Dutch_Defense', puzzleCount: 788 },
  { tag: 'Queens_Pawn_Game_Chigorin_Variation', puzzleCount: 751 },
  { tag: 'Sicilian_Defense_Smith-Morra_Gambit', puzzleCount: 743 },
  { tag: 'Caro-Kann_Defense_Exchange_Variation', puzzleCount: 721 },
  { tag: 'Four_Knights_Game_Italian_Variation', puzzleCount: 709 },
  { tag: 'Nimzo-Indian_Defense', puzzleCount: 703 },
  { tag: 'Petrovs_Defense', puzzleCount: 694 },
  { tag: 'Sicilian_Defense_McDonnell_Attack', puzzleCount: 692 },
  { tag: 'Queens_Gambit_Declined_Other_variations', puzzleCount: 681 },
  { tag: 'Ruy_Lopez_Berlin_Defense', puzzleCount: 648 },
  { tag: 'Scotch_Game_Scotch_Gambit', puzzleCount: 646 },
  { tag: 'Sicilian_Defense_Taimanov_Variation', puzzleCount: 645 },
  { tag: 'Queens_Gambit_Declined_Marshall_Defense', puzzleCount: 643 },
  { tag: 'Ruy_Lopez_Morphy_Defense', puzzleCount: 632 },
  { tag: 'Semi-Slav_Defense', puzzleCount: 622 },
  { tag: 'Sicilian_Defense_Other_variations', puzzleCount: 616 },
  { tag: 'Italian_Game_Anti-Fried_Liver_Defense', puzzleCount: 603 },
  { tag: 'English_Opening_Symmetrical_Variation', puzzleCount: 594 },
  { tag: 'Queens_Pawn_Game_London_System', puzzleCount: 586 },
  { tag: 'Sicilian_Defense_Open', puzzleCount: 584 },
  { tag: 'Center_Game', puzzleCount: 575 },
  { tag: 'Vant_Kruijs_Opening', puzzleCount: 575 },
  { tag: 'Vant_Kruijs_Opening_Other_variations', puzzleCount: 575 },
  { tag: 'Slav_Defense_Other_variations', puzzleCount: 555 },
  { tag: 'Ruy_Lopez_Steinitz_Defense', puzzleCount: 549 },
  { tag: 'Sicilian_Defense_French_Variation', puzzleCount: 536 },
  { tag: 'Queens_Pawn_Game_Colle_System', puzzleCount: 531 },
  { tag: 'Englund_Gambit_Other_variations', puzzleCount: 518 },
  { tag: 'Benoni_Defense_Old_Benoni', puzzleCount: 510 },
  { tag: 'Vienna_Game_Vienna_Gambit', puzzleCount: 510 },
  { tag: 'Hungarian_Opening', puzzleCount: 509 },
  { tag: 'Queens_Pawn_Game_Zukertort_Variation', puzzleCount: 500 },
  { tag: 'Scandinavian_Defense_Other_variations', puzzleCount: 500 },
  { tag: 'Sicilian_Defense_Accelerated_Dragon', puzzleCount: 499 },
  { tag: 'Indian_Defense_Budapest_Defense', puzzleCount: 492 },
  { tag: 'Three_Knights_Opening', puzzleCount: 490 },
  { tag: 'Italian_Game_Giuoco_Piano', puzzleCount: 481 },
  { tag: 'Sicilian_Defense_Nyezhmetdinov-Rossolimo_Attack', puzzleCount: 481 },
  { tag: 'English_Opening_Anglo-Indian_Defense', puzzleCount: 477 },
  { tag: 'French_Defense_Tarrasch_Variation', puzzleCount: 475 },
  { tag: 'Ponziani_Opening', puzzleCount: 475 },
  { tag: 'Elephant_Gambit', puzzleCount: 474 },
  { tag: 'Philidor_Defense_Exchange_Variation', puzzleCount: 469 },
  { tag: 'Sicilian_Defense_Dragon_Variation', puzzleCount: 464 },
  { tag: 'Caro-Kann_Defense_Two_Knights_Attack', puzzleCount: 463 },
  { tag: 'Three_Knights_Opening_Other_variations', puzzleCount: 439 },
  { tag: 'Sicilian_Defense_Kan_Variation', puzzleCount: 438 },
  { tag: 'Zukertort_Opening_Tennison_Gambit', puzzleCount: 435 },
  { tag: 'Blackmar-Diemer_Gambit', puzzleCount: 433 },
  { tag: 'Bishops_Opening_Other_variations', puzzleCount: 422 },
  { tag: 'Russian_Game_Stafford_Gambit', puzzleCount: 418 },
  { tag: 'Scotch_Game_Classical_Variation', puzzleCount: 409 },
  { tag: 'Polish_Opening', puzzleCount: 406 },
  { tag: 'Englund_Gambit_Complex', puzzleCount: 405 },
  { tag: 'Sicilian_Defense_Smith-Morra_Gambit_Accepted', puzzleCount: 402 },
  { tag: 'Nimzo-Larsen_Attack_Modern_Variation', puzzleCount: 395 },
  { tag: 'French_Defense_Normal_Variation', puzzleCount: 394 },
  { tag: 'Rapport-Jobava_System', puzzleCount: 389 },
  { tag: 'Rapport-Jobava_System_Other_variations', puzzleCount: 389 },
  { tag: 'Rat_Defense', puzzleCount: 387 },
  { tag: 'Italian_Game_Evans_Gambit', puzzleCount: 376 },
  { tag: 'English_Defense', puzzleCount: 370 },
  { tag: 'Trompowsky_Attack', puzzleCount: 370 },
  { tag: 'English_Defense_Other_variations', puzzleCount: 367 },
  { tag: 'Ruy_Lopez_Classical_Variation', puzzleCount: 362 },
  { tag: 'Bird_Opening_Other_variations', puzzleCount: 354 },
  { tag: 'Queens_Gambit_Declined_Albin_Countergambit', puzzleCount: 352 },
  { tag: 'Bishops_Opening_Berlin_Defense', puzzleCount: 349 },
  { tag: 'Caro-Kann_Defense_Classical_Variation', puzzleCount: 347 },
  { tag: 'Kings_Gambit_Declined_Queens_Knight_Defense', puzzleCount: 346 },
  { tag: 'Kings_Indian_Attack', puzzleCount: 346 },
  { tag: 'Russian_Game_Italian_Variation', puzzleCount: 344 },
  { tag: 'French_Defense_Rubinstein_Variation', puzzleCount: 342 },
  { tag: 'English_Opening_Agincourt_Defense', puzzleCount: 341 },
  { tag: 'Sicilian_Defense_Lowenthal_Variation', puzzleCount: 341 },
  { tag: 'Caro-Kann_Defense_Panov_Attack', puzzleCount: 335 },
  { tag: 'Danish_Gambit', puzzleCount: 333 },
  { tag: 'Danish_Gambit_Accepted', puzzleCount: 333 },
  { tag: 'Danish_Gambit_Other_variations', puzzleCount: 333 },
  { tag: 'Hungarian_Opening_Other_variations', puzzleCount: 329 },
  { tag: 'Kings_Indian_Defense_Normal_Variation', puzzleCount: 326 },
  { tag: 'Grunfeld_Defense', puzzleCount: 325 },
  { tag: 'Kings_Gambit', puzzleCount: 323 },
  { tag: 'Kings_Gambit_Other_variations', puzzleCount: 323 },
  { tag: 'Ruy_Lopez_Exchange_Variation', puzzleCount: 321 },
  { tag: 'Sicilian_Defense_Delayed_Alapin_Variation', puzzleCount: 321 },
  { tag: 'French_Defense_Winawer_Variation', puzzleCount: 320 },
  { tag: 'Nimzo-Larsen_Attack_Classical_Variation', puzzleCount: 317 },
  { tag: 'Vienna_Game_Stanley_Variation', puzzleCount: 317 },
  { tag: 'Italian_Game_Scotch_Gambit', puzzleCount: 315 },
  { tag: 'Scandinavian_Defense_Valencian_Variation', puzzleCount: 314 },
  { tag: 'Pirc_Defense_Classical_Variation', puzzleCount: 313 },
  { tag: 'Queens_Pawn_Game_Symmetrical_Variation', puzzleCount: 310 },
  { tag: 'French_Defense_Classical_Variation', puzzleCount: 305 },
  { tag: 'Grob_Opening', puzzleCount: 305 },
  { tag: 'Bird_Opening_Dutch_Variation', puzzleCount: 302 },
]

export const USEFUL_PUZZLE_OPENING_TAGS = new Set(PUZZLE_OPENING_TAG_COUNTS_GT300.map((x) => x.tag))

/**
 * Map a niche opening tag to the nearest useful ancestor tag present in puzzle DB.
 * Ex: Italian_Game_Two_Knights_Defense_Fried_Liver_Attack -> Italian_Game_Two_Knights_Defense
 */
export function normalizeToUsefulPuzzleTag(tag: string): string | null {
  let cur = tag.trim()
  if (!cur) return null
  while (cur.length > 0) {
    if (USEFUL_PUZZLE_OPENING_TAGS.has(cur)) return cur
    const i = cur.lastIndexOf('_')
    if (i === -1) break
    cur = cur.slice(0, i)
  }
  return null
}

